baseURL = 'https://lyysldzjc0087.github.io/'
#baseURL = 'http://localhost:1313/'
relativeURLs = true
canonifyURLs = false
uglyURLs = false
#title = 'AAA建材李姐 - 本地开发'
languageCode = 'en-us'
title = 'AAA建材李姐'
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 3

[params]
	mode="auto"# color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "哇 你怎么来视奸我了 [欢迎你一下](Insulindian-Phasmid/posts/my-first-post/)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

#入场页
#	showEntryPage = true

#	enableEntryPage = true
#	entryMessage = "简单开始"
#	entryDelay = 3
#	entryTarget = "/posts"
#

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lyysldzjc0087/Insulindian-Phasmid"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


#[[menu.main]]
#name = "欢迎页"
#url="/posts/entry"
